version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - rabbitmq

  celery_worker:
    build: .
    command: poetry run celery -A celery_tasks.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - app
      - mongodb
      - rabbitmq

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"